name: Metrics
on:
  # Atualiza as 00:00 todos os dias
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente na aba Actions
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token pessoal (não precisa configurar se usar o padrão, ele usa o do bot)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Configurações Visuais
          user: m4ntonio
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          plugin_lines: yes
